// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type mainBackend struct {
	_      structs.HostLayout
	Ip     uint32
	Port   uint16
	Active uint16
}

// loadMain returns the embedded CollectionSpec for main.
func loadMain() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MainBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load main: %w", err)
	}

	return spec, err
}

// loadMainObjects loads main and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mainObjects
//	*mainPrograms
//	*mainMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMainObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMain()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mainSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mainSpecs struct {
	mainProgramSpecs
	mainMapSpecs
	mainVariableSpecs
}

// mainProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mainProgramSpecs struct {
	LbMain *ebpf.ProgramSpec `ebpf:"lb_main"`
}

// mainMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mainMapSpecs struct {
	Backends  *ebpf.MapSpec `ebpf:"backends"`
	ConnCount *ebpf.MapSpec `ebpf:"conn_count"`
	HashRing  *ebpf.MapSpec `ebpf:"hash_ring"`
	LbPort    *ebpf.MapSpec `ebpf:"lb_port"`
}

// mainVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mainVariableSpecs struct {
}

// mainObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMainObjects or ebpf.CollectionSpec.LoadAndAssign.
type mainObjects struct {
	mainPrograms
	mainMaps
	mainVariables
}

func (o *mainObjects) Close() error {
	return _MainClose(
		&o.mainPrograms,
		&o.mainMaps,
	)
}

// mainMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMainObjects or ebpf.CollectionSpec.LoadAndAssign.
type mainMaps struct {
	Backends  *ebpf.Map `ebpf:"backends"`
	ConnCount *ebpf.Map `ebpf:"conn_count"`
	HashRing  *ebpf.Map `ebpf:"hash_ring"`
	LbPort    *ebpf.Map `ebpf:"lb_port"`
}

func (m *mainMaps) Close() error {
	return _MainClose(
		m.Backends,
		m.ConnCount,
		m.HashRing,
		m.LbPort,
	)
}

// mainVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMainObjects or ebpf.CollectionSpec.LoadAndAssign.
type mainVariables struct {
}

// mainPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMainObjects or ebpf.CollectionSpec.LoadAndAssign.
type mainPrograms struct {
	LbMain *ebpf.Program `ebpf:"lb_main"`
}

func (p *mainPrograms) Close() error {
	return _MainClose(
		p.LbMain,
	)
}

func _MainClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed main_bpfel.o
var _MainBytes []byte
